### ISSUE TITLE
UnboundLocalError: local variable 'renewlist' referenced before assignment

### ISSUE THREAD

**Issue by yashodhank** [Siaperas/Strawpoll-Voting-Bot#1]
```
$ python3 Main.py -v 10 -s hhhph2aa -t check14822349
Traceback (most recent call last):
  File "Main.py", line 244, in <module>
    Strawpoll_Multivote()
  File "Main.py", line 74, in __init__
    for i in renewlist:
UnboundLocalError: local variable 'renewlist' referenced before assignment
```

Python 3.4.2

```
$ pip3 install --upgrade requests
Collecting requests
  Downloading requests-2.18.4-py2.py3-none-any.whl (88kB)
    100% |████████████████████████████████| 92kB 2.7MB/s
Collecting certifi>=2017.4.17 (from requests)
  Downloading certifi-2017.7.27.1-py2.py3-none-any.whl (349kB)
    100% |████████████████████████████████| 358kB 2.8MB/s
Collecting chardet<3.1.0,>=3.0.2 (from requests)
  Downloading chardet-3.0.4-py2.py3-none-any.whl (133kB)
    100% |████████████████████████████████| 143kB 4.8MB/s
Collecting idna<2.7,>=2.5 (from requests)
  Downloading idna-2.6-py2.py3-none-any.whl (56kB)
    100% |████████████████████████████████| 61kB 7.6MB/s
Collecting urllib3<1.23,>=1.21.1 (from requests)
  Downloading urllib3-1.22-py2.py3-none-any.whl (132kB)
    100% |████████████████████████████████| 133kB 4.4MB/s
Installing collected packages: certifi, chardet, idna, urllib3, requests
Successfully installed certifi-2017.7.27.1 chardet-3.0.4 idna-2.6 requests-2.18.4 urllib3-1.22
```

**Comment by Siaperas** [comment]
Unfortunately the website from where I parsed the proxies stopped listing the proxies so I will have to find as soon as I can a new site from which I could parse the necessary info.

**Comment by Siaperas** [comment]
Changed the site from which the script receives its proxy list.
