### ISSUE TITLE
not sure what this error is 

### ISSUE THREAD

**Issue by orbital00** [Siaperas/Strawpoll-Voting-Bot#11]
[#] Number of proxies remaining in old list: 1413

[1] New proxy: 3.212.104.192:3128
[#] Connecting... 
[!] Voting failed for the specific proxy.
Traceback (most recent call last):
  File "Main.py", line 187, in webdriverManipulation
    chrome = webdriver.Chrome(options=chrome_options)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 76

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Main.py", line 266, in <module>
    Strawpoll_Multivote()
  File "Main.py", line 138, in __init__
    self.webdriverManipulation(proxy);
  File "Main.py", line 208, in webdriverManipulation
    chrome.quit()
UnboundLocalError: local variable 'chrome' referenced before assignment
Davids-MacBook-Pro:strawpoll-voting-bot david$

**Comment by Worf2340** [comment]
Did you ever fix your error? I had the same issue and solved it by matching the version of Chromedriver to my Chrome version.

**Comment by Th3R4nd0m** [comment]
Modified an old script that worked on the old strawpoll.me . Anyway,thanks =))

**Comment by asopiah** [comment]
@Th3R4nd0m  and @Worf2340 I am currenlty facing the same error as shown below. I tried matching the chromedriver and chrome version but all in vain. How else can I fix this.
`[#] Flushing usedProxies.txt file...
[#] Number of proxies remaining in old list: 398
()
[1] New proxy: 223.198.8.46:9999
[#] Connecting... 
[!] Voting failed for the specific proxy.
Traceback (most recent call last):
  File "Main.py", line 266, in <module>
    Strawpoll_Multivote()
  File "Main.py", line 138, in __init__
    self.webdriverManipulation(proxy);
  File "Main.py", line 208, in webdriverManipulation
    chrome.quit()
UnboundLocalError: local variable 'chrome' referenced before assignment`
@Th3R4nd0m Could be kind to share the old strawpoll.me script you modifed?
