### ISSUE TITLE
PLS HELP I NEED IT VERY SOON

### ISSUE THREAD

**Issue by yesriskk** [Siaperas/Strawpoll-Voting-Bot#13]
C:\Users\Connor\Desktop\Strawpoll-Voting-Bot-master>python Main.py -v  20 -s g6733eyd -t checkk4bd2zpzsyb1 -f -r
[#] Flushing usedProxies.txt file...
Traceback (most recent call last):
  File "Main.py", line 76, in __init__
    renewlist=self.renewProxyList();
  File "Main.py", line 257, in renewProxyList
    content = urllib.request.urlopen(url).read()
  File "C:\Users\Connor\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\Connor\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "C:\Users\Connor\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 640, in http_response
    response = self.parent.error(
  File "C:\Users\Connor\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "C:\Users\Connor\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 502, in _call_chain
    result = func(*args)
  File "C:\Users\Connor\AppData\Local\Programs\Python\Python38\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Main.py", line 266, in <module>
    Strawpoll_Multivote()
  File "Main.py", line 151, in __init__
    print("[!] " + ex.strerror + ": " + ex.filename)
TypeError: can only concatenate str (not "NoneType") to str

C:\Users\Connor\Desktop\Strawpoll-Voting-Bot-master>

**Comment by kalikim** [comment]
has anyone fixed the above error?

**Comment by HuskyCodez** [comment]
It throws a traceback because there is no file i think
