### ISSUE TITLE
TypeError: can only concatenate str (not "NoneType") to str

### ISSUE THREAD

**Issue by Piyushdhakad** [Siaperas/Strawpoll-Voting-Bot#14]
[#] Flushing usedProxies.txt file...
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/Strawpoll-Voting-Bot/Main.py", line 76, in __init__
    renewlist=self.renewProxyList();
  File "/data/data/com.termux/files/home/Strawpoll-Voting-Bot/Main.py", line 257, in renewProxyList
    content = urllib.request.urlopen(url).read()
  File "/data/data/com.termux/files/usr/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/data/data/com.termux/files/usr/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/data/data/com.termux/files/usr/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/data/data/com.termux/files/usr/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)                        File "/data/data/com.termux/files/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/data/data/com.termux/files/usr/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden       
During handling of the above exception, another exception occurred:                                             
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/Strawpoll-Voting-Bot/Main.py", line 266, in <module>
    Strawpoll_Multivote()
  File "/data/data/com.termux/files/home/Strawpoll-Voting-Bot/Main.py", line 151, in __init__
    print("[!] " + ex.strerror + ": " + ex.filename)
TypeError: can only concatenate str (not "NoneType") to str

**Comment by Ashishsingh009** [comment]
Same error I'm also getting
