### ISSUE TITLE
Its not working please see the output

### ISSUE THREAD

**Issue by WhatsMyDay** [Siaperas/Strawpoll-Voting-Bot#16]
[#] Flushing usedProxies.txt file...
Traceback (most recent call last):
  File "Main.py", line 76, in __init__
    renewlist=self.renewProxyList();
  File "Main.py", line 257, in renewProxyList
    content = urllib.request.urlopen(url).read()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Main.py", line 266, in <module>
    Strawpoll_Multivote()
  File "Main.py", line 151, in __init__
    print("[!] " + ex.strerror + ": " + ex.filename)
TypeError: can only concatenate str (not "NoneType") to str

That's my input below: 
python3.8 Main.py -d strawpoll.com -v 2000 -s 1y9g9w1pv -t 1qpwy7eor2rs -f -r

**Comment by WhatsMyDay** [comment]
same output when I also used it without the option -d
